# Traefik Helm Chart Values
# See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml for all available options

# Expose Traefik using a LoadBalancer service
service:
  type: LoadBalancer

# Enable the Kubernetes CRD provider
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
service:
  annotations:
    metallb.universe.tf/address-pool: "public-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.1.128"