apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:GabhenDM/homelab-v2.git
    path: k8s/infra/argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true       # remove resources no longer in Git
      selfHeal: true    # revert manual drifts
