apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: "1.6.0"
    helm:
      parameters:
      - name: defaultSettings.defaultDataPath
        value: "/var/longhorn"
      - name: preUpgradeChecker.jobEnabled
        value: "false"
      - name: ingress.enabled
        value: "true"
      - name: ingress.ingressClassName
        value: "traefik"
      - name: ingress.host
        value: "longhorn.internal.gabhendm.com"
      - name: ingress.path
        value: "/"
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
