apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: "v25.0.0" # Will be updated by the user if needed
    helm:
      valueFiles:
      - $values/k8s/infra/helm/traefik/values.yaml
  - repoURL: 'git@github.com:GabhenDM/homelab-v2.git'
    targetRevision: main
    ref: values
  - repoURL: 'git@github.com:GabhenDM/homelab-v2.git'
    targetRevision: main
    path: k8s/infra/manifests/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
